tetratelabs/getenvoy.io

site/themes/getenvoy/layouts/partials/features.html
=> Change features wording

site/content/blog/announcing-the-getenvoy-project.md, site/content/blog/using-getenvoy-with-traffic-director.md
Signed-off-by: Liam White <liam@tetrate.io>
=> [DONT MERGE] Fix dates for launch

site/content/github/_index.md
=> build the fix for builds of builds

README.md
Signed-off-by: Liam White <liam@tetrate.io>
=> Update readme to point at repo page

site/config.toml
Expected to go out at 10 AM PT today, don't merge yet.
=> 1.11.1 release

.gitignore, dist/_redirects
Signed-off-by: Liam White <liam@tetrate.io>
=> Add redirect for cli install

site/themes/getenvoy/static/css/main.css
See https://github.com/tetratelabs/getenvoy.io/issues/104#issuecomment-526550180
=> Fix copy pointer

.gitignore, dist/_redirects, site/static/_redirects
Signed-off-by: Liam White <liam@tetrate.io>
=> fix redirects being deleted in prod deploy

site/config.toml
=> Release 1.12.1

site/themes/getenvoy/static/css/main.css
This PR addresses issue on blog post view in mobile device. 
Signed-off-by: Adityo Pratomo <pratomo.adityo@gmail.com>
=> fix css for blog view on mobile device

site/content/install/cli/binary.md
Signed-off-by: Dhi Aurrahman <dio@tetrate.io>
=> content: Fix install CLI script path

site/config.toml
=> Update version to 1.12.2

site/config.toml
Signed-off-by: Cynthia <cynthia@coan.dev>
=> v1.13.1 release

site/config.toml
=> Release 1.14.1

site/config.toml
=> release 1.14.2

site/config.toml
=> releasa: 1.14.3

site/config.toml
=> release 1.15.0

site/themes/getenvoy/layouts/partials/quickstart.html, site/themes/getenvoy/static/css/main.css, site/themes/getenvoy/static/js/custom.js
=> Make clipboard always sticky

site/config.toml
Signed-off-by: Yaroslav Skopets <yaroslav@tetrate.io>
=> release: Envoy v1.15.1

site/config.toml
=> release 1.16.0

site/config.toml
=> release 1.16.1

site/config.toml
=> release 1.17.0

site/config.toml
Signed-off-by: Takeshi Yoneda <takeshi@tetrate.io>
=> Release 1.17.1

site/static/_redirects
See https://github.com/tetratelabs/getenvoy/pull/234
=> Sets up redirects for envoy_versions.json

site/static/_redirects, site/static/robots.txt
https://github.com/tetratelabs/getenvoy/pull/244
=> Changes envoy versions json from snake_case to kebab-case

site/content/github/_index.md
=> Fixes broken GitHub page

site/static/_redirects, site/themes/func-e/layouts/partials/quickstart.html
this is better than 404s and redirects
=> Bounces all dead links to /index.html and serves /install.sh from Netlify
